name: release
run-name: ${{ github.actor }} is generating a new PR
on: [pull_request]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

  

jobs: 
  get-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.3' 
      - name: Get dependencies
        run: pip install python-dotenv && pip install openai
      - name: Generate commits
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          bash ./scripts/commit_generator.sh
          git push -f origin HEAD:${{ github.head_ref }}